//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montagsmaler.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Montagsmaler.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client verbunden! ähnelt.
        /// </summary>
        internal static string clientManagerConnect {
            get {
                return ResourceManager.GetString("clientManagerConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client hat die Verbindung verloren! ähnelt.
        /// </summary>
        internal static string clientManagerDisconnect {
            get {
                return ResourceManager.GetString("clientManagerDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client wird geschlossen... ähnelt.
        /// </summary>
        internal static string clientManagerShutdown {
            get {
                return ResourceManager.GetString("clientManagerShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client gestartet! ähnelt.
        /// </summary>
        internal static string clientManagerStarted {
            get {
                return ResourceManager.GetString("clientManagerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Listener Thread ist fertig! ähnelt.
        /// </summary>
        internal static string listenerThreadFinished {
            get {
                return ResourceManager.GetString("listenerThreadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbehandelte Message: {0} ähnelt.
        /// </summary>
        internal static string listenerUnhandledMessage {
            get {
                return ResourceManager.GetString("listenerUnhandledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung zu Server verloren! ähnelt.
        /// </summary>
        internal static string lostConnectionToServer {
            get {
                return ResourceManager.GetString("lostConnectionToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbehandelter Datentyp: {0} ähnelt.
        /// </summary>
        internal static string managerUnhandledPacketType {
            get {
                return ResourceManager.GetString("managerUnhandledPacketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbehandelte StatusChangeMessage: {0} ähnelt.
        /// </summary>
        internal static string managerUnhandledStatusChange {
            get {
                return ResourceManager.GetString("managerUnhandledStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erklärung:
        ///In dem Spiel Montagsmaler wird einem Spieler ein Wort vorgegeben, das er zeichnen muss.
        ///Die anderen müssen dieses Wort erraten um Punkte zu verdienen.
        ///Derjenige, der das Wort errät erhält 100 Punkte, derjenige der gezeichnet hat 50.
        ///Wurde das Wort bis Ende des Zeitlimits nicht erraten erhält niemand Punkte. ähnelt.
        /// </summary>
        internal static string openingSceneExplanation {
            get {
                return ResourceManager.GetString("openingSceneExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spielerklärung ähnelt.
        /// </summary>
        internal static string openingSceneExplanationTitle {
            get {
                return ResourceManager.GetString("openingSceneExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Montagsmaler
        ///Geschrieben von Benedikt Strasser
        ///c 2016 ähnelt.
        /// </summary>
        internal static string openingSceneInfo {
            get {
                return ResourceManager.GetString("openingSceneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string openingSceneInfoTitle {
            get {
                return ResourceManager.GetString("openingSceneInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter PacketType: {0} ähnelt.
        /// </summary>
        internal static string packetUnknownPacketType {
            get {
                return ResourceManager.GetString("packetUnknownPacketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Port 4333 ist bereits belegt. ähnelt.
        /// </summary>
        internal static string portError {
            get {
                return ResourceManager.GetString("portError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben sie eine gültige IP Addresse ein. ähnelt.
        /// </summary>
        internal static string searchSceneWrongIp {
            get {
                return ResourceManager.GetString("searchSceneWrongIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du bist dran.
        ///Das zu erratende Wort ist: {0} ähnelt.
        /// </summary>
        internal static string serverManagerGuessWordMessage {
            get {
                return ResourceManager.GetString("serverManagerGuessWordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Spieler mit der IP: {0} ist an der Reihe. ähnelt.
        /// </summary>
        internal static string serverManagerNextPlayerMessage {
            get {
                return ResourceManager.GetString("serverManagerNextPlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Spieler mit der IP: {0} hat das Wort erraten! ähnelt.
        /// </summary>
        internal static string serverManagerPlayerGuessedWordMessage {
            get {
                return ResourceManager.GetString("serverManagerPlayerGuessedWordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server wird geschlossen... ähnelt.
        /// </summary>
        internal static string serverManagerShutdown {
            get {
                return ResourceManager.GetString("serverManagerShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server gestartet auf Port: {0} ähnelt.
        /// </summary>
        internal static string serverManagerStarted {
            get {
                return ResourceManager.GetString("serverManagerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitlimit überschritten! Nächste Runde... ähnelt.
        /// </summary>
        internal static string serverManagerTimeOverMessage {
            get {
                return ResourceManager.GetString("serverManagerTimeOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Spiel ist zu Ende. 
        ///Gewonnen hat/haben:
        /// ähnelt.
        /// </summary>
        internal static string serverManagerWinMessage {
            get {
                return ResourceManager.GetString("serverManagerWinMessage", resourceCulture);
            }
        }
    }
}
